### ISSUE TITLE
connection breaking during scrape

### ISSUE THREAD

**Issue by taylerpauls** [ScriptSmith/instaphyte#1]
Hi! if my connection breaks during a scrape of a certain hashtag (example after 1500 posts are downloaded.) can i somehow specifiy a range of posts so i can continue downloading from where my connection breaks at ? that way i dont have to redownload everything i already have

**Comment by ScriptSmith** [comment]
SocialReaper is built to tolerate failed requests for about a minute before
timing out. Are you finding issues with the way it works currently? If so,
I could try make that last a bit longer or build in some 'pausing' mechanism

**Comment by taylerpauls** [comment]
A little longer would be nice, maybe 5 minutes or even if it would skip that post and go to the next one.

**Comment by ScriptSmith** [comment]
I've updated v1.0.1 to wait longer and retry more when requesting resources from the API. 

Unfortunately you can't ask it to restart or skip forward in time because there's no timecode-based pagination, and if your connection was lost the regular pagination would likely fail because too much time has passed.

I've also made it skip thumbnails that have already been downloaded, and failed requests for thumbnails will now be skipped
